apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrolebinding.yml
- deployment.yml
- service.yml
- serviceaccount.yml
commonLabels:
  app.kubernetes.io/name: clouddriver
configMapGenerator:
- behavior: create
  name: clouddriver
  files:
  - files/clouddriver.yml

